language: 'python'

python:
  - '3.6.6'

install:
  - pip install -r requirements.txt

before_script:
- psql -c 'create database store_tests;' -U catherine_store

script:
- pytest
- coverage run --source=app.api.v2 -m pytest && coverage report

after_success:
- coveralls